# Generated by Django 2.2.14 on 2020-07-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_series_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='Image',
            new_name='image',
        ),
    ]
